# Eliminação de Gauss

A cada passo k, procura-se zerar todos os elementos da coluna k abaixo da linha k (fazer ser triangular superior)

### Resolvendo Ax = b

Para resolver, ...

In [11]:
import numpy as np

In [12]:
def gauss_elimination(A, b):
    C = np.concatenate((A, b.T), axis=1)
    for k in range(C.shape[0]-1):
        m = np.expand_dims(C[k+1:, k] / C[k, k], -1)
        C[k+1:, k:] -= m @ np.expand_dims(C[k, k:], 0)
    return C[:, :-1], C[:, -1]

In [13]:
def solve_gauss(A, b):
    A, b = gauss_elimination(A, b)
    x = np.zeros(A.shape[0])
    for i in range(A.shape[0]-1, -1, -1):
        x[i] = (b[i] - np.dot(x, A[i, :])) / A[i, i]
    return x

In [14]:
A = np.array([[1, 2, 0], [1, 3, 1], [-2, 0, 1]]).astype('float64')
b = np.array([[3, 5, -1]]).astype('float64')
print(gauss_elimination(A, b))
solve_gauss(A, b)

(array([[ 1.,  2.,  0.],
       [ 0.,  1.,  1.],
       [ 0.,  0., -3.]]), array([ 3.,  2., -3.]))


array([1., 1., 1.])

### Relação com a decomposição L.U

Ao final da eliminação de Gauss, se consegue uma matriz superior, que será a **U**.

Ou seja, temos:

$$E_1 \cdot E_2 \cdots E_n \cdot A = U$$

Portanto:

$$L = E_1^{-1} \cdot E_2^{-1} \cdots E_n^{-1}$$

# Eliminação de Gauss com Pivoteamento Parcial

1. A cada passo **K**, antes da etapa de eliminação, encontre *p* \in [k, n] tal que é o max da coluna
2. Permutar as linhas p e k

In [15]:
import numpy as np

In [16]:
def gauss_elimination_partial(A, b):
    return

In [17]:
A = np.array([[1, 2, 0], [1, 3, 1], [-2, 0, 1]]).astype('float64')
b = np.array([[3, 5, -1]]).astype('float64')
print(gauss_elimination_partial(A, b))
solve_gauss(A, b)

None


array([1., 1., 1.])

### Como ficaria a decomposição L.U agora que sabemos fazer pivoteamento parcial?

- P.A = L.U, onde P é uma matriz permutação

### Resolvendo Ax = b

$$(PA)x = (LU)x = Pb$$

$$Ly = Pb$$

$$Ux = y$$