# Cálculo da inversa de uma matriz

Seja A $\in$ $\mathbb{M}_n(\mathbb{R})$

$$A^{-1} = [v_1 v_2 \cdots v_n]$$
Em que $v_k$ são as colunas da matriz inversa.

Assim,

$$A A^{-1} = I$$
$$A [v_1 v_2 \cdots v_n] = [e_1 e_2 \cdots e_n] $$ (Copiar a foto)

Logo, basta resolver $n$ sistemas lineares $A \cdot v_i = e_i$

In [11]:
import numpy as np

from ipynb.fs.full.LU import lu_decomposition
from ipynb.fs.full.LU import lower_solve
from ipynb.fs.full.LU import upper_solve

In [12]:
def inverse_matrix(A):
    L, U = lu_decomposition(A)    
    return A

In [13]:
A = np.array([[1, 2, 0], [1, 3, 1], [-2, 0, 1]]).astype('float64')
print(inverse_matrix(A))

[[ 1.  2.  0.]
 [ 1.  3.  1.]
 [-2.  0.  1.]]
