In [1]:
import numpy as np

In [2]:
def lu_decomposition(A):
    n = A.shape[0]
    
    U = np.zeros_like(A)
    L = np.zeros_like(A)
    
    for j in range(n):
        L[j][j] = 1.0
        
        for i in range(j+1):
            sum = 0
            for k in range(i):
                sum += U[k][j] * L[i][k]
            U[i][j] = A[i][j] - sum
        
        for i in range(j, n):
            sum = 0
            for k in range(j):
                sum += U[k][j] * L[i][k]
            L[i][j] = (A[i][j] - sum) / U[j][j]
    
    return L, U

In [3]:
# A * x = C
def lower_solve(A, c):
    return A    

In [4]:
# A * x = C
def upper_solve(A, c):
    return A    

In [5]:
A = np.array([[1, 2, 0], [1, 3, 1], [-2, 0, 1]]).astype('float64')
L, U = lu_decomposition(A)
print(L)
print()
print(U)

[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [-2.  4.  1.]]

[[ 1.  2.  0.]
 [ 0.  1.  1.]
 [ 0.  0. -3.]]
